name: base
channels:
  - conda-forge
dependencies:
  - brotlipy=0.7.0
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - colorama=0.4.4
  - conda=4.10.3
  - conda-package-handling=1.7.3
  - cryptography=3.4.7
  - idna=3.1
  - libcxx=12.0.1
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.2.2
  - pycosat=0.6.3
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.9.6
  - python_abi=3.9
  - readline=8.1
  - requests=2.26.0
  - ruamel_yaml=0.15.80
  - setuptools=49.6.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - tqdm=4.62.0
  - tzdata=2021a
  - urllib3=1.26.6
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
